runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /scripts
  static_dir: scripts
- url: /style
  static_dir: style
- url: /.*
  script: main.app
  login: optional

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
